// Copyright 2026 The tiktok_auth authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum PlatformErrorKind {
  success,
  cancelled,
  denied,
  misconfigured,
  alreadyInProgress,
  network,
  failed,
}

class PlatformAuthRequest {
  PlatformAuthRequest({
    required this.clientKey,
    required this.redirectUri,
    required this.scopes,
    required this.state,
    required this.preferWebAuth,
    required this.disableAutoAuth,
    this.language,
  });

  String clientKey;

  String redirectUri;

  List<String> scopes;

  String state;

  bool preferWebAuth;

  bool disableAutoAuth;

  String? language;

  List<Object?> _toList() {
    return <Object?>[
      clientKey,
      redirectUri,
      scopes,
      state,
      preferWebAuth,
      disableAutoAuth,
      language,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformAuthRequest decode(Object result) {
    result as List<Object?>;
    return PlatformAuthRequest(
      clientKey: result[0]! as String,
      redirectUri: result[1]! as String,
      scopes: (result[2]! as List<Object?>).cast<String>(),
      state: result[3]! as String,
      preferWebAuth: result[4]! as bool,
      disableAutoAuth: result[5]! as bool,
      language: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformAuthRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(clientKey, other.clientKey) &&
        _deepEquals(redirectUri, other.redirectUri) &&
        _deepEquals(scopes, other.scopes) &&
        _deepEquals(state, other.state) &&
        _deepEquals(preferWebAuth, other.preferWebAuth) &&
        _deepEquals(disableAutoAuth, other.disableAutoAuth) &&
        _deepEquals(language, other.language);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformAuthRequest(clientKey: $clientKey, redirectUri: $redirectUri, scopes: $scopes, state: $state, preferWebAuth: $preferWebAuth, disableAutoAuth: $disableAutoAuth, language: $language)';
  }
}

class PlatformAuthResult {
  PlatformAuthResult({
    required this.errorKind,
    required this.usedWebAuth,
    required this.grantedScopes,
    this.authCode,
    this.codeVerifier,
    this.state,
    this.expectedState,
    this.redirectUri,
    this.nativeCode,
    this.errorDescription,
  });

  PlatformErrorKind errorKind;

  bool usedWebAuth;

  List<String> grantedScopes;

  String? authCode;

  String? codeVerifier;

  String? state;

  String? expectedState;

  String? redirectUri;

  String? nativeCode;

  String? errorDescription;

  List<Object?> _toList() {
    return <Object?>[
      errorKind,
      usedWebAuth,
      grantedScopes,
      authCode,
      codeVerifier,
      state,
      expectedState,
      redirectUri,
      nativeCode,
      errorDescription,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformAuthResult decode(Object result) {
    result as List<Object?>;
    return PlatformAuthResult(
      errorKind: result[0]! as PlatformErrorKind,
      usedWebAuth: result[1]! as bool,
      grantedScopes: (result[2]! as List<Object?>).cast<String>(),
      authCode: result[3] as String?,
      codeVerifier: result[4] as String?,
      state: result[5] as String?,
      expectedState: result[6] as String?,
      redirectUri: result[7] as String?,
      nativeCode: result[8] as String?,
      errorDescription: result[9] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformAuthResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(errorKind, other.errorKind) &&
        _deepEquals(usedWebAuth, other.usedWebAuth) &&
        _deepEquals(grantedScopes, other.grantedScopes) &&
        _deepEquals(authCode, other.authCode) &&
        _deepEquals(codeVerifier, other.codeVerifier) &&
        _deepEquals(state, other.state) &&
        _deepEquals(expectedState, other.expectedState) &&
        _deepEquals(redirectUri, other.redirectUri) &&
        _deepEquals(nativeCode, other.nativeCode) &&
        _deepEquals(errorDescription, other.errorDescription);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformAuthResult(errorKind: $errorKind, usedWebAuth: $usedWebAuth, grantedScopes: $grantedScopes, authCode: $authCode, codeVerifier: $codeVerifier, state: $state, expectedState: $expectedState, redirectUri: $redirectUri, nativeCode: $nativeCode, errorDescription: $errorDescription)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PlatformErrorKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is PlatformAuthRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is PlatformAuthResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformErrorKind.values[value];
      case 130:
        return PlatformAuthRequest.decode(readValue(buffer)!);
      case 131:
        return PlatformAuthResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class TikTokAuthHostApi {
  /// Constructor for [TikTokAuthHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TikTokAuthHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<String>> validateConfiguration(
    String clientKey,
    String redirectUri,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tiktok_auth_ios.TikTokAuthHostApi.validateConfiguration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[clientKey, redirectUri],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  Future<bool> isTikTokInstalled() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tiktok_auth_ios.TikTokAuthHostApi.isTikTokInstalled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<PlatformAuthResult> authorize(PlatformAuthRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tiktok_auth_ios.TikTokAuthHostApi.authorize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PlatformAuthResult;
  }

  Future<PlatformAuthResult?> takePendingResult() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.tiktok_auth_ios.TikTokAuthHostApi.takePendingResult$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as PlatformAuthResult?;
  }
}
