// Copyright 2026 The tiktok_auth authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.tiktokauth.android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class PlatformErrorKind(val raw: Int) {
  SUCCESS(0),
  CANCELLED(1),
  DENIED(2),
  MISCONFIGURED(3),
  ALREADY_IN_PROGRESS(4),
  NETWORK(5),
  FAILED(6);

  companion object {
    fun ofRaw(raw: Int): PlatformErrorKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformAuthRequest (
  val clientKey: String,
  val redirectUri: String,
  val scopes: List<String>,
  val state: String,
  val preferWebAuth: Boolean,
  val disableAutoAuth: Boolean,
  val language: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformAuthRequest {
      val clientKey = pigeonVar_list[0] as String
      val redirectUri = pigeonVar_list[1] as String
      val scopes = pigeonVar_list[2] as List<String>
      val state = pigeonVar_list[3] as String
      val preferWebAuth = pigeonVar_list[4] as Boolean
      val disableAutoAuth = pigeonVar_list[5] as Boolean
      val language = pigeonVar_list[6] as String?
      return PlatformAuthRequest(clientKey, redirectUri, scopes, state, preferWebAuth, disableAutoAuth, language)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clientKey,
      redirectUri,
      scopes,
      state,
      preferWebAuth,
      disableAutoAuth,
      language,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformAuthRequest
    return MessagesPigeonUtils.deepEquals(this.clientKey, other.clientKey) && MessagesPigeonUtils.deepEquals(this.redirectUri, other.redirectUri) && MessagesPigeonUtils.deepEquals(this.scopes, other.scopes) && MessagesPigeonUtils.deepEquals(this.state, other.state) && MessagesPigeonUtils.deepEquals(this.preferWebAuth, other.preferWebAuth) && MessagesPigeonUtils.deepEquals(this.disableAutoAuth, other.disableAutoAuth) && MessagesPigeonUtils.deepEquals(this.language, other.language)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clientKey)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.redirectUri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.scopes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.state)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.preferWebAuth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.disableAutoAuth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.language)
    return result
  }
  override fun toString(): String {
    return "PlatformAuthRequest(clientKey=$clientKey, redirectUri=$redirectUri, scopes=$scopes, state=$state, preferWebAuth=$preferWebAuth, disableAutoAuth=$disableAutoAuth, language=$language)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformAuthResult (
  val errorKind: PlatformErrorKind,
  val usedWebAuth: Boolean,
  val grantedScopes: List<String>,
  val authCode: String? = null,
  val codeVerifier: String? = null,
  val state: String? = null,
  val expectedState: String? = null,
  val redirectUri: String? = null,
  val nativeCode: String? = null,
  val errorDescription: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformAuthResult {
      val errorKind = pigeonVar_list[0] as PlatformErrorKind
      val usedWebAuth = pigeonVar_list[1] as Boolean
      val grantedScopes = pigeonVar_list[2] as List<String>
      val authCode = pigeonVar_list[3] as String?
      val codeVerifier = pigeonVar_list[4] as String?
      val state = pigeonVar_list[5] as String?
      val expectedState = pigeonVar_list[6] as String?
      val redirectUri = pigeonVar_list[7] as String?
      val nativeCode = pigeonVar_list[8] as String?
      val errorDescription = pigeonVar_list[9] as String?
      return PlatformAuthResult(errorKind, usedWebAuth, grantedScopes, authCode, codeVerifier, state, expectedState, redirectUri, nativeCode, errorDescription)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      errorKind,
      usedWebAuth,
      grantedScopes,
      authCode,
      codeVerifier,
      state,
      expectedState,
      redirectUri,
      nativeCode,
      errorDescription,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformAuthResult
    return MessagesPigeonUtils.deepEquals(this.errorKind, other.errorKind) && MessagesPigeonUtils.deepEquals(this.usedWebAuth, other.usedWebAuth) && MessagesPigeonUtils.deepEquals(this.grantedScopes, other.grantedScopes) && MessagesPigeonUtils.deepEquals(this.authCode, other.authCode) && MessagesPigeonUtils.deepEquals(this.codeVerifier, other.codeVerifier) && MessagesPigeonUtils.deepEquals(this.state, other.state) && MessagesPigeonUtils.deepEquals(this.expectedState, other.expectedState) && MessagesPigeonUtils.deepEquals(this.redirectUri, other.redirectUri) && MessagesPigeonUtils.deepEquals(this.nativeCode, other.nativeCode) && MessagesPigeonUtils.deepEquals(this.errorDescription, other.errorDescription)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorKind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.usedWebAuth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.grantedScopes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.codeVerifier)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.state)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.expectedState)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.redirectUri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.nativeCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorDescription)
    return result
  }
  override fun toString(): String {
    return "PlatformAuthResult(errorKind=$errorKind, usedWebAuth=$usedWebAuth, grantedScopes=$grantedScopes, authCode=$authCode, codeVerifier=$codeVerifier, state=$state, expectedState=$expectedState, redirectUri=$redirectUri, nativeCode=$nativeCode, errorDescription=$errorDescription)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformErrorKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformAuthRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformAuthResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PlatformErrorKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformAuthRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PlatformAuthResult -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TikTokAuthHostApi {
  fun validateConfiguration(clientKey: String, redirectUri: String): List<String>
  fun isTikTokInstalled(): Boolean
  suspend fun authorize(request: PlatformAuthRequest): PlatformAuthResult
  fun takePendingResult(): PlatformAuthResult?

  companion object {
    /** The codec used by TikTokAuthHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `TikTokAuthHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TikTokAuthHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tiktok_auth_android.TikTokAuthHostApi.validateConfiguration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientKeyArg = args[0] as String
            val redirectUriArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.validateConfiguration(clientKeyArg, redirectUriArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tiktok_auth_android.TikTokAuthHostApi.isTikTokInstalled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isTikTokInstalled())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tiktok_auth_android.TikTokAuthHostApi.authorize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PlatformAuthRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.authorize(requestArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tiktok_auth_android.TikTokAuthHostApi.takePendingResult$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.takePendingResult())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
