// Copyright 2026 The tiktok_auth authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum PlatformErrorKind: Int, CaseIterable {
  case success = 0
  case cancelled = 1
  case denied = 2
  case misconfigured = 3
  case alreadyInProgress = 4
  case network = 5
  case failed = 6
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformAuthRequest: Hashable, CustomStringConvertible {
  var clientKey: String
  var redirectUri: String
  var scopes: [String]
  var state: String
  var preferWebAuth: Bool
  var disableAutoAuth: Bool
  var language: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformAuthRequest? {
    let clientKey = pigeonVar_list[0] as! String
    let redirectUri = pigeonVar_list[1] as! String
    let scopes = pigeonVar_list[2] as! [String]
    let state = pigeonVar_list[3] as! String
    let preferWebAuth = pigeonVar_list[4] as! Bool
    let disableAutoAuth = pigeonVar_list[5] as! Bool
    let language: String? = nilOrValue(pigeonVar_list[6])

    return PlatformAuthRequest(
      clientKey: clientKey,
      redirectUri: redirectUri,
      scopes: scopes,
      state: state,
      preferWebAuth: preferWebAuth,
      disableAutoAuth: disableAutoAuth,
      language: language
    )
  }
  func toList() -> [Any?] {
    return [
      clientKey,
      redirectUri,
      scopes,
      state,
      preferWebAuth,
      disableAutoAuth,
      language,
    ]
  }
  static func == (lhs: PlatformAuthRequest, rhs: PlatformAuthRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.clientKey, rhs.clientKey) && MessagesPigeonInternal.deepEquals(lhs.redirectUri, rhs.redirectUri) && MessagesPigeonInternal.deepEquals(lhs.scopes, rhs.scopes) && MessagesPigeonInternal.deepEquals(lhs.state, rhs.state) && MessagesPigeonInternal.deepEquals(lhs.preferWebAuth, rhs.preferWebAuth) && MessagesPigeonInternal.deepEquals(lhs.disableAutoAuth, rhs.disableAutoAuth) && MessagesPigeonInternal.deepEquals(lhs.language, rhs.language)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformAuthRequest")
    MessagesPigeonInternal.deepHash(value: clientKey, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: redirectUri, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: scopes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: preferWebAuth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: disableAutoAuth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: language, hasher: &hasher)
  }

  public var description: String {
    return "PlatformAuthRequest(clientKey: \(String(describing: clientKey)), redirectUri: \(String(describing: redirectUri)), scopes: \(String(describing: scopes)), state: \(String(describing: state)), preferWebAuth: \(String(describing: preferWebAuth)), disableAutoAuth: \(String(describing: disableAutoAuth)), language: \(String(describing: language)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformAuthResult: Hashable, CustomStringConvertible {
  var errorKind: PlatformErrorKind
  var usedWebAuth: Bool
  var grantedScopes: [String]
  var authCode: String? = nil
  var codeVerifier: String? = nil
  var state: String? = nil
  var expectedState: String? = nil
  var redirectUri: String? = nil
  var nativeCode: String? = nil
  var errorDescription: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformAuthResult? {
    let errorKind = pigeonVar_list[0] as! PlatformErrorKind
    let usedWebAuth = pigeonVar_list[1] as! Bool
    let grantedScopes = pigeonVar_list[2] as! [String]
    let authCode: String? = nilOrValue(pigeonVar_list[3])
    let codeVerifier: String? = nilOrValue(pigeonVar_list[4])
    let state: String? = nilOrValue(pigeonVar_list[5])
    let expectedState: String? = nilOrValue(pigeonVar_list[6])
    let redirectUri: String? = nilOrValue(pigeonVar_list[7])
    let nativeCode: String? = nilOrValue(pigeonVar_list[8])
    let errorDescription: String? = nilOrValue(pigeonVar_list[9])

    return PlatformAuthResult(
      errorKind: errorKind,
      usedWebAuth: usedWebAuth,
      grantedScopes: grantedScopes,
      authCode: authCode,
      codeVerifier: codeVerifier,
      state: state,
      expectedState: expectedState,
      redirectUri: redirectUri,
      nativeCode: nativeCode,
      errorDescription: errorDescription
    )
  }
  func toList() -> [Any?] {
    return [
      errorKind,
      usedWebAuth,
      grantedScopes,
      authCode,
      codeVerifier,
      state,
      expectedState,
      redirectUri,
      nativeCode,
      errorDescription,
    ]
  }
  static func == (lhs: PlatformAuthResult, rhs: PlatformAuthResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.errorKind, rhs.errorKind) && MessagesPigeonInternal.deepEquals(lhs.usedWebAuth, rhs.usedWebAuth) && MessagesPigeonInternal.deepEquals(lhs.grantedScopes, rhs.grantedScopes) && MessagesPigeonInternal.deepEquals(lhs.authCode, rhs.authCode) && MessagesPigeonInternal.deepEquals(lhs.codeVerifier, rhs.codeVerifier) && MessagesPigeonInternal.deepEquals(lhs.state, rhs.state) && MessagesPigeonInternal.deepEquals(lhs.expectedState, rhs.expectedState) && MessagesPigeonInternal.deepEquals(lhs.redirectUri, rhs.redirectUri) && MessagesPigeonInternal.deepEquals(lhs.nativeCode, rhs.nativeCode) && MessagesPigeonInternal.deepEquals(lhs.errorDescription, rhs.errorDescription)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformAuthResult")
    MessagesPigeonInternal.deepHash(value: errorKind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: usedWebAuth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: grantedScopes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: authCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: codeVerifier, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: expectedState, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: redirectUri, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: nativeCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: errorDescription, hasher: &hasher)
  }

  public var description: String {
    return "PlatformAuthResult(errorKind: \(String(describing: errorKind)), usedWebAuth: \(String(describing: usedWebAuth)), grantedScopes: \(String(describing: grantedScopes)), authCode: \(String(describing: authCode)), codeVerifier: \(String(describing: codeVerifier)), state: \(String(describing: state)), expectedState: \(String(describing: expectedState)), redirectUri: \(String(describing: redirectUri)), nativeCode: \(String(describing: nativeCode)), errorDescription: \(String(describing: errorDescription)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformErrorKind(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return PlatformAuthRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return PlatformAuthResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PlatformErrorKind {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformAuthRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformAuthResult {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TikTokAuthHostApi {
  func validateConfiguration(clientKey: String, redirectUri: String) throws -> [String]
  func isTikTokInstalled() throws -> Bool
  func authorize(request: PlatformAuthRequest) async throws -> PlatformAuthResult
  func takePendingResult() throws -> PlatformAuthResult?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TikTokAuthHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `TikTokAuthHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TikTokAuthHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let validateConfigurationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tiktok_auth_ios.TikTokAuthHostApi.validateConfiguration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      validateConfigurationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientKeyArg = args[0] as! String
        let redirectUriArg = args[1] as! String
        do {
          let result = try api.validateConfiguration(clientKey: clientKeyArg, redirectUri: redirectUriArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      validateConfigurationChannel.setMessageHandler(nil)
    }
    let isTikTokInstalledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tiktok_auth_ios.TikTokAuthHostApi.isTikTokInstalled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isTikTokInstalledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isTikTokInstalled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isTikTokInstalledChannel.setMessageHandler(nil)
    }
    let authorizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tiktok_auth_ios.TikTokAuthHostApi.authorize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authorizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PlatformAuthRequest
        Task { @MainActor in
          do {
            let result = try await api.authorize(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      authorizeChannel.setMessageHandler(nil)
    }
    let takePendingResultChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tiktok_auth_ios.TikTokAuthHostApi.takePendingResult\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      takePendingResultChannel.setMessageHandler { _, reply in
        do {
          let result = try api.takePendingResult()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      takePendingResultChannel.setMessageHandler(nil)
    }
  }
}
